### PR TITLE
Create Variant-title-of-manifestation.md

### PR DESCRIPTION
**Pull request by jess-grz**
I hope I got the numbering and example formatting right! My first foray with the revised element template.

### CODE REVIEW

**Comment by ladylazarus3** [comment]
it is the most beautiful MD file i have ever seen!!! keep em, comin dear!
Long haul trucker, indeed.
k&A

**Comment by jess-grz** [comment]
:-D

**Comment by rarebkcat** [comment]
It is definitely time for happy hour! (Shhhh, just because it's 10 / 11 o'clock on Sunday, that's no matter -- it just means it's mimosa happy hour!)

kalan and I went through this, and we did a few things:

- the numbering at the end is super long, and it wraps around. However, the fourth component of the citation is a decimal, not a whole number, so .91 follows .9. We renumbered the last citations, so they go to .993 right now. (XD ) During a subsequent phase of the internal review, it's all getting a Grand Renumbering, and we'll spread the citation numbers out a bit for elements with lots of instructions, like this one. (And it's a weird thing to wrap your head around! kalan's reminded me of it multiple times.)

- In the examples, we put in the element name, Variant title of manifestation, as the label, instead of "additional title access point". This aligns the example with the name of the RDA element / the element instructions we're in. 

-Amy & kalan

**Comment by jess-grz** [comment]
All sounds good, thanks! And nothing wrong with a little brunch happy hour. 😉

**Pull request merged**
