### PR TITLE
Update Title-of-manifestation.md

### PR DESCRIPTION
**Pull request by jess-grz**
Updated placeholder text with finalized text from Gdoc

### CODE REVIEW

**Comment by ladylazarus3** [comment]
Hi there, we've been trying to place 'Sources of information' and 'Form and order of information' on the [chapter level](https://rbms-bsc.github.io/DCRMR/title/) pages.  Does this [Title of manifestation](https://rbms-bsc.github.io/DCRMR/title/Title-of-manifestation/) need this information in both places (i.e. on  [Title of manifestation](https://rbms-bsc.github.io/DCRMR/title/Title-of-manifestation/) and at the [chapter level](https://rbms-bsc.github.io/DCRMR/title/) ?)

Let me know what you folks think and thanks for the update. :)

kalan

**Comment by jess-grz** [comment]
Thanks, Kalan! I don't think the info needs to be in both places; there
doesn't seem to be a need to deviate from the pattern you've set up. You
can move "Sources of information" and "Form and order of info" to the Title
chapter page. If we end up thinking we need it in both places, we can
always copy it over again.

**Comment by ladylazarus3** [comment]
Sure thing!  Here is the GitHub issue on [sources of information](https://github.com/rbms-bsc/DCRMR/issues/15), please re-open the issue discussion thread as needed. :)

**Comment by jess-grz** [comment]
Got it, thank you!

**Comment by rarebkcat** [comment]
THanks, Jessica!

We did go ahead an pull out the information about sources of information and form and order of information, since that's on the chapter pages. Additionally, we transferred one of the examples in those sections to the Title chapter page.

One more down, woot!

-A&k

**Pull request merged**
