### PR TITLE
Create Integrity-of-the-copy.md

### PR DESCRIPTION
**Pull request by jess-grz**
I think I'm getting it!

### CODE REVIEW

**Comment by ladylazarus3** [comment]
You are totally getting it! :)  You are amazing! :)  Amy and i are going to wait until Friday to Merge new pull requests to the Master and write the documentation for that process.  So please don't worry if you don't hear from us right away, you are doing great.  i look forward to seeing you all this afternoon. :)  Thanks for tackling another one! :) :)
kalan

**Comment by jess-grz** [comment]
Awesome, thanks, Kalan! See you this afternoon. :)

**Comment by ladylazarus3** [comment]
Jessica, Amy and i ran out of steam on Friday to get to this one, but we hope to get to it this Friday.  If you'd like, feel free to work on more.  the only thing i noticed with this one is that "chapter-name" should be changed to "introduction" in the Yaml header.  i have it on my to do list to add a helpful reference list of all the chapter names so folks can find them easier, but for prelims the chapter names will either be "preface" "introduction" or "general-rules" (all lowercase with hyphens).

**Comment by ladylazarus3** [comment]
and thank you again for your wonderful help! :) :)  so appreciated! :)

**Comment by jess-grz** [comment]
No worries, thanks, Kalan! Sorry about that very obvious error with the YAML chapter name 😬 Sometimes you can’t see the trees for the forest, I suppose. I’m going to try to get to another one today.

Thanks for all of your help and patience!
Jessica

**Comment by ladylazarus3** [comment]
Now the file looks perfect!  Thanks, also i've added a column to the [Order-of-the-text spreadsheet](https://docs.google.com/spreadsheets/d/1nP4uJPxj6gbfWPcPusKxAqxBXbQW9HG8uoU1SxZMqq0/edit#gid=820222028) for Yaml header chapter conventions... since we've shortened a few of the chapter names in the URLs, it is nice to have a handy list of all the options. :)  Thank you again for your awesome work! :)

kalan

**Comment by jess-grz** [comment]
That's a great idea, thanks again, Kalan!

**Comment by ladylazarus3** [comment]
Jessica, this looks perfect.  Thanks again for your patience with us!  Thanks and feel free to tackle a few more if you have the time! :)  We really, really appreciate your wonderful help!

kalan

**Comment by jess-grz** [comment]
Thanks so much, Kalan! I’ll definitely tackle some more. Have a great weekend!

**Pull request merged**
