### PR TITLE
Create Statement-of-responsibility-relating-to-title-proper.md

### PR DESCRIPTION
**Pull request by ladylazarus3**
May need some citation updates.  i'm a little burnt out... so many apologies in advance if i've misspelled "statement of responsibility relating to title proper" a bajillion times.  hopefully we will catch them all with the broken link checker.  feel free to fix anything needing fixing.

### CODE REVIEW

**Comment by jess-grz** [comment]
Ok, I'll take a look!

**Comment by rarebkcat** [comment]
Hi, @jess-grz --

Sundry comments!

The RDA definition on Statement of responsibility relating to title proper that was given was the RDA definition for [Statement of responsibility](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-a39c4ac1-03cb-351b-8868-f64d7dd16de4), not [Statement of responsibility relating to title proper](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-93929207-c91d-3970-b325-af8fd9dd2956). Although we agree that the definition of Statement of responsibility is more useful, we did change it to match the RDA definition.

At 2.20.5.1, "Transposition of statements of responsibility," we changed the instruction to be "Made a Note on statement of responsibility" instead of "Make a note on manifestation." (This is like the change we mentioned in the [Other title information comment](https://github.com/rbms-bsc/DCRMR/pull/110#issuecomment-699648964), also touching on issue #105 .)

At 2.20.96, "Statements of responsibility with grammatically inseparable elements," we suggest adding the following instruction to make the PPDM instructions and the SoR instructions match:

> If a statement with grammatically inseparable elements contains information relating both to the publication, distribution, or manufacture of the resource and to the agents who have contributed to its intellectual or artistic content, use judgment in deciding whether to transcribe the statement as part of the [Publication statement](https://rbms-bsc.github.io/DCRMR/ppdm/Publication-statement/), [Distribution statement](https://rbms-bsc.github.io/DCRMR/ppdm/Distribution-statement/), or [Manufacture statement](https://rbms-bsc.github.io/DCRMR/ppdm/Manufacture-statement/) or as a statement of responsibility (see [4.20.8.4](https://rbms-bsc.github.io/DCRMR/ppdm/Publication-statement/#4.20.8.4), [4.21.7.4](https://rbms-bsc.github.io/DCRMR/ppdm/Distribution-statement/#4.21.7.4), [4.22.7.4](https://rbms-bsc.github.io/DCRMR/ppdm/Manufacture-statement/#4.22.7.4)). Often the layout of the source will suggest the appropriate treatment.

`<a name="2.20.96.2">2.20.96.2</a> If a statement with grammatically inseparable elements contains information relating both to the publication, distribution, or manufacture of the resource and to the agents who have contributed to its intellectual or artistic content, use judgment in deciding whether to transcribe the statement as part of the [Publication statement](/DCRMR/ppdm/Publication-statement/), [Distribution statement](/DCRMR/ppdm/Distribution-statement/), or [Manufacture statement](/DCRMR/ppdm/Manufacture-statement/) or as a statement of responsibility (see [4.20.8.4](/DCRMR/ppdm/Publication-statement/#4.20.8.4), [4.21.7.4](/DCRMR/ppdm/Distribution-statement/#4.21.7.4) [4.22.7.4](/DCRMR/ppdm/Manufacture-statement/#4.22.7.4)). Often the layout of the source will suggest the appropriate treatment.
`

(Note that we did not make this change.) 

Best,
Amy & kalan

**Comment by jess-grz** [comment]
Several element pages for Title and SOR were in a rougher draft than others. We’ll definitely want to comb through to harmonize language throughout DCRMR.

**Comment by rarebkcat** [comment]
The entire text needs a good comb through -- so many people have worked on it for so long, and there are so many layers of decisions that have been made! (And they really start in 2012, not with the current configuration of the editorial group -- we're trying to bring the Policy Statements and DCRMB4 and post-3R RDA into alignment, and it's a lot!) 

We just wanted to make sure we mentioned to you differing outcomes, especially when they touched on open issues. (We also wanted to document the changes somewhere in case someone was wondering "wait, why / when did that change?" There have been enough time that we've backtracked changes through the layers of documents that explicitly stating what happened seemed worthwhile!)

Finally, if it's wanted, we can restore the original text, but we also need to make sure the connected pieces of text are also updated, since it's all an interconnected web.

(Plus there have to be so many repetitive instructions across elements. You can write one thing in DCRM(B) and have it apply to several elements, but the atomization of RDA is a bit of a nightmare sometimes.)

Also (and I don't think we mentioned it in any of our comments today), we really appreciate all the work y'all have put into this -- we know it's a lot!

(@jess-grz I don't know if you're subscribed, so tagging you in case you're not. XD)

**Comment by jess-grz** [comment]
Thanks so much for taking the time to document the changes! I know it’s a lot of work to make the changes, let alone document what you’ve done. This is going to be so helpful for future review. You two are the best!

**Pull request merged**
