### PR TITLE
Update Other-title-information.md

### PR DESCRIPTION
**Pull request by ladylazarus3**

### CODE REVIEW

**Comment by ladylazarus3** [comment]
Drafted pull request with permission of Title/SOR chapters working group.  Folks, feel free to make changes as needed and commit those changes to the branch.  Thanks! :)

kalan

**Comment by rarebkcat** [comment]
@jess-grz 

Hi, Jessica--

kalan and I are working on Other title information, and we made a switch in a reference.

In the google doc of Note on title, the instruction is: "Make a note indicating the transposition of other title information that precedes the title proper on the title page (see Other title information, X.X.)" This is now at [1.27.91.1](https://rbms-bsc.github.io/DCRMR/title/Note-on-title/#1.27.91.1) and committed to the DCRMR text. 

In the google doc of Other title information, the instruction is: "If the other title information appears on the title page preceding or following text associated with another element of the description, transpose it to the other title information unless it is a grammatically inseparable part of the other element. When transposing the other title information, do not use the mark of omission. Make a **Note on manifestation** indicating the transposition." (This will be at 1.23.25.3, once the text is committed.) 

We switched the instruction at 1.23.25.3 to point to Note on title, with reciprocal references between 1.27.91.1 and 1.23.25.3. This is congruent with the other element instructions across chapters. 

However, we wanted to mention it because it 1) is an edit that changes outcome (as opposed to our usual edits, which are for consistency) and 2) it touches upon issue #105, which comes (we presume) from conversations the Title/SoR group has been having.

Best,
Amy & kalan

**Comment by jess-grz** [comment]
Thanks again for taking the time to make these changes!

**Comment by rarebkcat** [comment]
Hi, @jess-grz!

There was a subsequent change due to the edits at 1.23.25.3, with contents going to Note on manifestation.

In 1.23.9, "Abridgment of other title information," the instruction, was: "Optionally, if other title information is very lengthy and can be abridged without loss of essential information, omit less important words or phrases, using the mark of omission. If considered important, transcribe omitted words or phrases in a note on title (including the other titles or phrases referred to in 1D2.3 [i.e. 1.23.25.3, which is the contents])."

However, the contents notes in 1.23.25.3 is now a Note on manifestation, not a Note on title. therefore, we changed the text as 1.23.9 to a See also reference, not a See reference, as they're two different kinds of notes.

An additional thing we noticed, at 1.23.5.1, "Other title information constituting a formal statement of contents" is that the instruction is in Other title information; however, it also gives instruction for other elements (namely, title and SoR elements), without being replicated in those elements.

The google doc text read: "If other title information, or some portion of it, constitutes a formal statement of the contents of the work, and is grammatically separable from the title proper and other title information, transcribe it in a Note on title if considered important (see X.X.). When these formal statements are omitted from the **title proper** and **statement of responsibility relating to title proper elements**, use the mark of omission."

However, Title proper and Statement of reponsibility relating to title proper elements lack corresponding instructions.

For now, we edited the text at 1.23.5.1 to mirror the text at 7.20.5.1, and 1.23.5.1: "If other title information, or some portion of it, constitutes a formal statement of the contents of the work, and is grammatically separable from the title proper and other title information, transcribe it in a [Note on manifestation](https://rbms-bsc.github.io/DCRMR/Other-notes/Note-on-manifestation/) if considered important (see [7.20.5.1](https://rbms-bsc.github.io/DCRMR/other-notes/Note-on-manifestation/#7.20.5.1)). When these formal statements are omitted from the [Title of manifestation](https://rbms-bsc.github.io/DCRMR/title/Title-of-manifestation/) and [Statement of responsibility](https://rbms-bsc.github.io/DCRMR/sor/) elements and their subelements, use the mark of omission."

It might be that we want corresponding instructions on the chapter pages or on the element pages. *shrug emoji* Right now, we were just trying to get things into alignment. 

Thanks,
Amy & kalan

**Comment by jess-grz** [comment]
I think a lot of these inconsistencies are going to show up. We’re all going to have quite a bit to do during the internal review. Thanks for catching these and getting a head start!

**Pull request merged**
